In [1]:
import datasets
from datasets import load_dataset
import pandas as pd
import re
from utils import *


In [2]:

data = pd.read_parquet("data.parquet")

FileNotFoundError: [Errno 2] No such file or directory: 'data.parquet'

In [31]:
def key_signature(x):
    m=re.search(r'K:(?P<key>[A-G]\w*)',x)
    if m:
        return m.group('key')
    else:
        return 'Missing'

In [32]:
key_signature(data['abc notation'][1])

'C'

In [34]:
data['key'] = data['abc notation'].apply(key_signature)

In [35]:
data[data['key']=='Missing']

abc notation  \
181     X:182\nL:1/8\nQ:1/8=80\nM:9/8\nK:none\n|:{g} A...   
294     X:295\nL:1/8\nQ:1/8=80\nM:6/8\nK:none\n|:{g} B...   
378     X:379\nL:1/8\nQ:1/8=80\nM:4/4\nK:none\n a |{ef...   
1133    X:1134\nL:1/4\nQ:1/8=80\nM:4/4\nK:none\n{g} A/...   
1573    X:1574\nL:1/8\nM:4/4\nK:none\n [Be]16 |"^(ryth...   
...                                                   ...   
212818  X:212819\nL:1/8\nQ:1/8=80\nM:4/4\nK:none\n|: A...   
213644  X:213645\nL:1/8\nQ:1/8=80\nM:6/8\nK:none\n{gef...   
213659  X:213660\nL:1/16\nQ:1/4=72\nM:2/4\nK:none\n e2...   
213871  X:213872\nL:1/8\nQ:1/2=90\nM:2/4\nK:none\n|: D...   
214024  X:214025\nL:1/4\nQ:1/8=80\nM:3/4\nK:none\n|: a...   

                                             control code      key  
181                                  S:2\nB:4\nE:5\nB:8\n  Missing  
294                                  S:2\nB:8\nE:7\nB:8\n  Missing  
378     S:4\nB:9\nE:6\nB:8\nE:5\nE:6\nB:8\nE:6\nE:6\nE...  Missing  
1133                                          S:1\nB:20\n  Missing  
1573    S:4\nB:2\nE:1\nB:8\nE:1\nE:4\nB:8\nE:1\nE:4\nE...  Missing  
...                                                   ...      ...  
212818                               S:2\nB:9\nE:8\nB:9\n  Missing  
213644                               S:2\nB:8\nE:6\nB:9\n  Missing  
213659  S:4\nB:9\nE:6\nB:9\nE:7\nE:8\nB:9\nE:5\nE:6\nE...  Missing  
213871                               S:2\nB:8\nE:5\nB:8\n  Missing  
214024                                        S:1\nB:17\n  Missing  

[938 rows x 3 columns]

In [39]:
print(data.loc[294]['abc notation'])

X:295
L:1/8
Q:1/8=80
M:6/8
K:none
|:{g} B3{GdGe} B3 |{g} f2{GdG} f{gfg}f>ec |{g} A3{GAG} A3 |{gcd} c3/2{g}B/{d}c{gBd}B3/2{G}A/B | 
{Gdc} d3{gef} e3 |{g} f>ga{cd}c3/2{g}B/{d}A |{g} B3/2{d}c/f{gef}e>dc |{g} B3{GdGe} B3 :| 
{g} f3{GdG} f3 |{gef} e>fa{fg}f>ec |{g} A2{GdGe} A{gef} e2 c |{g} f2{GdG} f{gef}e>dc | 
{g} B3{Gdc} d3 |{gef} e>fa{cd}c3/2{g}B/{d}A |{g} B3/2{d}c/f{gef}e>dc |{g} B3{GdGe} B3 :|


In [68]:
tune = data.loc[1]['abc notation']

In [69]:
P=Patchilizer()

In [71]:
len(P.split_bars(tune))

25

In [73]:
encoded = P.encode(tune)

In [74]:
[len(x) for x in encoded]

[32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32]

In [75]:
[P.patch2bar(x) for x in encoded]

['X:2\n',
 'L:1/4\n',
 'M:3/4\n',
 'K:C\n',
 ' G |',
 ' E3/2 E/ E |',
 ' G2 G |',
 ' c2 c |',
 ' G2 G |',
 ' G2 c/>c/ |',
 ' B2 d |',
 ' d3 |',
 ' c2 G |',
 ' e2 e |',
 ' e d c |',
 ' B2 A |',
 ' A2 A |',
 ' \n B2 B |',
 ' d2 d |',
 ' d3 |',
 ' c2 G |',
 ' e2 e |',
 ' e d c |',
 ' B2 A |',
 ' A2 A |',
 ' B2 B |',
 ' d2 d |',
 ' d3 |',
 ' c2 |]']

In [76]:
P.decode(encoded)

'X:2\nL:1/4\nM:3/4\nK:C\n G | E3/2 E/ E | G2 G | c2 c | G2 G | G2 c/>c/ | B2 d | d3 | c2 G | e2 e | e d c | B2 A | A2 A | \n B2 B | d2 d | d3 | c2 G | e2 e | e d c | B2 A | A2 A | B2 B | d2 d | d3 | c2 |]'

In [77]:
P.encode('X:2\n')

[[1,
  88,
  58,
  50,
  10,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0]]

In [78]:
ord('X')

88

In [79]:
ord('2')

50

In [80]:
ord(':')

58

In [83]:
list(filter(None,['a','b','c',None]))

['a', 'b', 'c']

In [88]:
torch.nn.functional.one_hot(torch.tensor([[1,0,0],[0,1,0],[0,0,1]]),num_classes=2)

tensor([[[0, 1],
         [1, 0],
         [1, 0]],

        [[1, 0],
         [0, 1],
         [1, 0]],

        [[1, 0],
         [1, 0],
         [0, 1]]])

In [91]:
p=P.encode(tune)

In [92]:
torch.tensor(p)

tensor([[  1,  88,  58,  50,  10,   2,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  1,  76,  58,  49,  47,  52,  10,   2,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  1,  77,  58,  51,  47,  52,  10,   2,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  1,  75,  58,  67,  10,   2,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  1,  32,  71,  32, 124,   2,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  1,  32,  69,  51,  47,  50,  32,  69,  47,  32,  

In [95]:
z=torch.nn.functional.one_hot(torch.tensor(p),num_classes=128)

In [94]:
for i in range(128):
    print(chr(i))










	























 
!
"
#
$
%
&
'
(
)
*
+
,
-
.
/
0
1
2
3
4
5
6
7
8
9
:
;
<
=
>
?
@
A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
Z
[
\
]
^
_
`
a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z
{
|
}
~



In [96]:
z.shape

torch.Size([29, 32, 128])

In [98]:
z.reshape(len(p), -1,32*128)

tensor([[[0, 1, 0,  ..., 0, 0, 0]],

        [[0, 1, 0,  ..., 0, 0, 0]],

        [[0, 1, 0,  ..., 0, 0, 0]],

        ...,

        [[0, 1, 0,  ..., 0, 0, 0]],

        [[0, 1, 0,  ..., 0, 0, 0]],

        [[0, 1, 0,  ..., 0, 0, 0]]])